### ISSUE TITLE
Build logic

### ISSUE THREAD

**Issue by fauxmight** [justinesmithies/sxmo-alarm#5]
I did not make a pull request on this because I may be in error.

It appears to me that in the sxmo-alarm script after pulling the git code, config.def.h is overwriting a user-made config.h if it **is** present instead of making a config.h if **none** is present

This line 

`if [ -f config.def.h ] && [ -f config.h ]; then`

seems it should be

`if [ -f config.def.h ] && ! [ -f config.h ]; then`

If I am misunderstanding the logic here, let me know and close the issue.

**Comment by justinesmithies** [comment]
Hmm yeah I think you could be onto something there although I think that it should be as follows.

`if [ -f config.def.h ] && [ ! -f config.h ]; then`

I'll test this first before commiting any changes though.

**Comment by fauxmight** [comment]
Both ways function correctly in sh.
I cannot find a clear answer as to preferred or 'proper' arrangement.

**Comment by justinesmithies** [comment]
Committed your suggested changes @fauxmight after testing and all seems OK so I'm closing this now.
