### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Silent-Hunter** [justinesmithies/sxmo-alarm#6]
The build part errors with `CMake Error: The source directory "/home/alarm/build-sxmo-dev/sxmo-dmenu" does not appear to contain CMakeLists.txt`

It didn't do this a couple weeks ago the last time I tried out Arch.

**Comment by Silent-Hunter** [comment]
I think perhaps SXMO's repo has changed a lot since this script was last updated.

**Comment by Silent-Hunter** [comment]
Okay, I fixed it, it was a coding error in the latest dmenu.c

There is another issue though, some scripts need to be edited to use systemctl instead of rc-service, otherwise the modem doesn't work at all.

**Comment by Silent-Hunter** [comment]
I can't figure out how to fix this unfortunately, I tried changing all the `rc-service` stuff to `systemctl` but it still happens.

**Comment by justinesmithies** [comment]
Yes I see the sxmo devs have been busy porting it to Wayland which unfortunately has broken my script. I'm off on holiday on Thursday for a week but will get to trying to resolve all the new issues asap.

**Comment by Silent-Hunter** [comment]
Yes they have! Fortunately they've decided to keep both X and Wayland support side by side. Have a fun holiday.

**Comment by Silent-Hunter** [comment]
I'll give it a try tomorrow! I had to go back to PostmarketOS because Arch was using up the battery a bit faster, but I will try on an SD card just so I can help you test.

**Comment by Alumniminium** [comment]
> Hopefully if all of the above issues are now resolved as i've been working with the sxmo devs this evening to fix this. make sure to do a sudo ./sxmo-alarm.sh --force when you try again.

I had to delete the build folder too, i think it was svkb that didn't work with "cant fast forward"

**Comment by Silent-Hunter** [comment]
Seems to work now! Brightness controls need a new program called "light" to be installed. It's in the Arch repo.

**Comment by Silent-Hunter** [comment]
I don't know if this is the right place to mention this, but there's also no echo cancellation on speakerphone like there was in PostmarketOS. My friend can hear himself louder than me when using it.
