### ISSUE TITLE
Updating breaks the install.

### ISSUE THREAD

**Issue by Alumniminium** [justinesmithies/sxmo-alarm#9]
If you're running an update right now, you'll end up in a login loop, login screen keeps coming back.

**Comment by twigsdw** [comment]
Yup, it reads the login as ok, but gives this error:

which: no sxmo_deviceprofile_pinephone-1.2pine64.sh in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
no dbus cache file: /home/alarm/.cache/sxmo/dbus.bus...
